name: Update Jobs Daily

on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  update-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Timestamp
        run: |
          echo "Last Update: $(date)" > last-update.txt

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update jobs" || echo "No changes"

      - name: Push Changes
        run: |
          git push
